apiVersion: v1
kind: Service
metadata:
  name: mysql-service-lab
spec:
  selector:
    app: mysql-lab
  ports:
    - protocol: TCP
      port: 3306  # Le port sur lequel le service est exposé
      targetPort: 3306  # Le port sur lequel le conteneur écoute
  type: ClusterIP  # Le service est accessible à l'intérieur du cluster
