apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2
spec:
  capacity:
    storage: 1Gi  # Capacité de stockage
  accessModes:
    - ReadWriteOnce  # Mode d'accès
  hostPath:  # Type de volume (pour un usage local)
    path: /data/mysql  # Chemin sur l'hôte
